language: node_js
node_js:
  - 13

services:
  - docker

#Pre-testing installs
install:
  - echo "nothing needs to be installed"

#Scripts to be run such as tests
before_script:
  - echo "no tests... yet"

script:
  - docker --version  # document the version travis is using
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  #Tagging
  - docker tag udagram-reverseproxy lukorito/udagram-reverseproxy:latest
  - docker tag udagram-api-feed lukorito/udagram-api-feed:latest
  - docker tag udagram-api-user lukorito/udagram-api-user:latest
  - docker tag udagram-frontend lukorito/udagram-frontend:local

#Tasks to be run after success. In this case, push to docker hub
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push lukorito/udagram-reverseproxy
  - docker push lukorito/udagram-api-feed
  - docker push lukorito/udagram-api-user
  - docker push lukorito/udagram-frontend:local
