apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
spec:
  selector:
    matchLabels:
      run: api-user
  replicas: 2
  template:
    metadata:
      labels:
        run: api-user
    spec:
      containers:
      - name: api-user
        image: docker.io/lukorito/udagram-api-user:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 200Mi
          requests:
            cpu: 200m


---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: api-user
  name: api-user
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: api-user